rg_name = "rg01-b1"
nic_name = "nic1"
tag_env = "Dev"
vm_name = "VM01"
vm_size = "Standard_DS1_v2"
os_disk_name = "myosdisk1"
computer_name  = "hostname"
admin_username = "testadmin"
vm_pwd = "Password1234!"
region = "East US"  
subnet_id = ""

